# Eigenvalues and Eigenvectors using numpy

## Eigenvalues

### Without user's input

In [2]:
import numpy as np

In [22]:
matrix1=[[2,1,1],[2,3,4],[-1,-1,-2]]
#matrix1=[[1,2],[2,3]]
np.linalg.eigvals(matrix1)

array([ 3.,  1., -1.])

### With user's input

In [12]:
R1=int(input("Enter the number of rows of your matrix:"))
C1=int(input("Enter the number of columns of your matrix:"))

matrix1=[]
print("Enter the values row-wise.")

for i in range(R1):
    x=[]
    for j in range(C1):
        x.append(int(input()))
    matrix1.append(x)

print("This is your matrix.")
for m in range(R1):
    for n in range(C1):
        print(matrix1[m][n], end = " ")
    print()

p=np.linalg.eigvals(matrix1)
print("Your matix' eigenvalues are",p)

Enter the number of rows of your matrix:3
Enter the number of columns of your matrix:3
Enter the values row-wise.
2
1
1
2
3
4
-1
-1
-2
This is your matrix.
2 1 1 
2 3 4 
-1 -1 -2 
Your matix' eigenvalues are [ 3.  1. -1.]


## Eigenvalues and Eigenvectors

### Without user's input

In [20]:
matrix1=[[1,4],[3,2]]
np.linalg.eigh(matrix1)

(array([-1.54138127,  4.54138127]),
 array([[-0.76301998,  0.6463749 ],
        [ 0.6463749 ,  0.76301998]]))

### With user's input

In [24]:
R1=int(input("Enter the number of rows of your matrix:"))
C1=int(input("Enter the number of columns of your matrix:"))

matrix1=[]
print("Enter the values row-wise.")

for i in range(R1):
    x=[]
    for j in range(C1):
        x.append(int(input()))
    matrix1.append(x)

print("This is your matrix.")
for m in range(R1):
    for n in range(C1):
        print(matrix1[m][n], end = " ")
    print()

print("Your matix' eigenvalues and eigenvectors are.")
np.linalg.eigh(matrix1)

Enter the number of rows of your matrix:2
Enter the number of columns of your matrix:2
Enter the values row-wise.
1
4
3
2
This is your matrix.
1 4 
3 2 
Your matix' eigenvalues and eigenvectors are.


(array([-1.54138127,  4.54138127]),
 array([[-0.76301998,  0.6463749 ],
        [ 0.6463749 ,  0.76301998]]))